CREATE TABLE IF NOT EXISTS public.event_reminder_intent_outbox (
    sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id uuid NOT NULL UNIQUE,
    schema_version smallint NOT NULL DEFAULT 1 CHECK (schema_version = 1),
    intent_type varchar(64) NOT NULL CHECK (intent_type = 'event_reminder'),
    operation varchar(32) NOT NULL CHECK (operation IN ('schedule_upsert', 'schedule_cancel')),
    event_id bigint NOT NULL,
    start_time timestamptz NULL,
    reminder_offset_minutes jsonb NULL,
    occurred_at timestamptz NOT NULL,
    CONSTRAINT event_reminder_intent_payload_check CHECK (
        (operation = 'schedule_upsert' AND start_time IS NOT NULL
            AND jsonb_typeof(reminder_offset_minutes) = 'array'
            AND jsonb_array_length(reminder_offset_minutes) > 0)
        OR
        (operation = 'schedule_cancel' AND start_time IS NULL AND reminder_offset_minutes IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_event_reminder_intent_outbox_event_sequence
    ON public.event_reminder_intent_outbox (event_id, sequence DESC);

CREATE INDEX IF NOT EXISTS idx_event_reminder_intent_outbox_occurred_at
    ON public.event_reminder_intent_outbox (occurred_at);
