services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - ../.env
    depends_on:
      - redis
      - mongo
      - db
    restart: unless-stopped
    volumes:
      - ../backend:/app  # Монтируем весь код
      - /app/tmp        # Исключаем tmp директорию из синхронизации
    networks:
      - appnet
  telegram-bot:
    build:
      context: ../bot
      dockerfile: Dockerfile
    environment:
      - ../.env
    ports:
    - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - appnet
  notify_service:
    build:
      context: ../notify_service
      dockerfile: Dockerfile
    volumes:
      - ../notify_service/.env:/app/.env  # монтируем файл внутрь контейнера
    env_file:
      - ../notify_service/.env
    ports:
    - "8083:8080"
    depends_on:
      - db
      - telegram-bot
    restart: unless-stopped
    networks:
      - appnet


networks:
  appnet:
    driver: bridge