# Этап сборки
FROM golang:1.24-alpine AS builder

WORKDIR /app

# Копируем go.mod и go.sum для кеша зависимостей
COPY go.mod go.sum ./
RUN go mod download

# Копируем весь код
COPY . .

# Собираем бинарник
RUN go build -o main .

# Финальный минимальный образ
FROM alpine:latest

WORKDIR /app

# Копируем бинарник из builder-а
COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]

