import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Alexandria } from "next/font/google"; // <-- Добавляем импорты
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Новые шрифты:
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

const alexandria = Alexandria({
  variable: "--font-alexandria",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ru">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${inter.variable}
          ${alexandria.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
